// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { NativeModules, Platform } from "react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Cancels all pending scheduled notifications.
 * @returns {Promise.<void>}
 */
export async function CancelAllScheduledNotifications() {
	// BEGIN USER CODE
    // Documentation https://github.com/zo0r/react-native-push-notification
    const isIOS = Platform.OS === "ios";
    if (NativeModules &&
        ((isIOS && !NativeModules.RNCPushNotificationIOS) || (!isIOS && !NativeModules.RNPushNotification))) {
        return Promise.reject(new Error("Notifications module is not available in your app"));
    }
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const RNPushNotification = require("react-native-push-notification");
    RNPushNotification.cancelAllLocalNotifications();
    return Promise.resolve();
	// END USER CODE
}
