// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} notificationId - This field is required.
 * @returns {Promise.<boolean>}
 */
export async function CancelScheduledNotification(notificationId) {
	// BEGIN USER CODE
    const firebase = require("react-native-firebase");
    if (!notificationId) {
        throw new TypeError("Input parameter 'Notification id' is required");
    }
    firebase.notifications().cancelNotification(notificationId);
    return true;
	// END USER CODE
}
